apiVersion: v1
kind: Pod
metadata:
  name: my-web-pod
  labels:
    app: web
spec:
  containers:
  - name: nginx-container
    image: cr.yandex/mirror/library/nginx:alpine
    ports:
    - containerPort: 80
